# Site settings
title: *oldborn
email: s.safak.topcu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Wild Developer, Rurouini Academician, Game Designer Wannabe, Vegetarian.
baseurl: ''
url:  ''
twitter_username: ssafaktopcu
github_username: oldborn

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  pet-projects:
    output: true
    permalink: /pet-projects/:path/
  games:
    output: true
    permalink: /games/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
